apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: prepare-db
          image: userforpython47/backend:2
          command: ['/bin/bash']
          args:
            - -c
            - >- 
              until [ $(timeout 2 bash -c "</dev/tcp/$POSTGRES_SERVER.default.svc.cluster.local/$POSTGRES_PORT" ; echo $?) -eq 0 ]; 
              do echo "Waiting for $POSTGRES_SERVER to be ready"; sleep 2; done &&
              bash scripts/prestart.sh
          envFrom:
          - configMapRef:
              name: backend-configmap
      containers:
      - name: backend
        image: userforpython47/backend:2
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 250m
            memory: 500Mi
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: backend-configmap
        livenessProbe:
          httpGet:
            path: /api/v1/utils/health-check/
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 3
      