version: 0.2

phases:
  pre_build:
    commands:
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
      - aws --version

  build:
    commands:
      - cd infra
      - echo "Initializing Terraform..."
      - terraform init -no-color
      - echo "Validating Terraform code..."
      - terraform validate
      - echo "Planning Terraform actions..."
      - terraform plan -out=tfplan

  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - infra/*
