version: 0.2

phases:

  build:
    commands:
      - cd infra
      - echo "Initializing Terraform..."
      - terraform init -no-color
      - echo "given terraform action for terraform is $ACTION"
      - test \"$ACTION\" = "destroy" && (echo "Action was to destroy" && terraform destroy -auto-approve) || (echo "Planning Terraform actions..." && terraform apply -auto-approve tfplan) 

  post_build:
    commands:
      - echo "Deploy completed"

