version: 0.2

phases:
  pre_build:
    commands:
      - echo "Restoring cached Terraform data if available..."
      - mkdir -p .terraform

  build:
    commands:
      - cd infra
      - echo "Initializing Terraform..."
      - terraform init
      - echo "Validating Terraform code..."
      - terraform validate
      - echo "Planning Terraform actions..."
      - terraform plan -out=tfplan

  post_build:
    commands:
      - echo "Build completed. Caching .terraform* and tfplan"

cache:
  paths:
    - .terraform/**/*         # Terraform providers/modules
    - .terraform.lock.hcl     # Lock file
    - tfplan                  # Terraform plan file

artifacts:
  files:
    - plan/tfplan
