version: 0.2

phases:

  build:
    commands:
      - cd infra
      - echo "Initializing Terraform..."
      - terraform init -no-color
      - echo "Planning Terraform actions..."
      - terraform apply tfplan -auto-approve 

  post_build:
    commands:
      - echo "Deploy completed"

