version: 0.2

phases:
  build:
    commands:
      - echo "Deploying to AWS"
      - cd infra
      - terraform init -no-color
      - terraform apply tfplan -auto-approve

  post_build:
    commands:
      - echo "Deploy completed"
