version: 0.2

phases:

  pre_build:
    commands:
      - echo "Installing uv"
      - curl -LsSf https://astral.sh/uv/install.sh | sh
      - echo "Installing project dependencies"
      - source $HOME/.local/bin/env
      - cd app/backend && uv sync
      - echo "Activating virtualenv"
      - source .venv/bin/activate
  build:
    commands:
      - echo "Starting services with docker compose"
      - docker compose up -d
      - echo "Executing tests"
      - until [[ $(netstat -tlpn | grep 8000) ]]; do echo "waiting service"; sleep 2; done 
      - netstat -tlpn
      - curl localhost:8000
      - curl localhost:5432
      - docker compose exec backend bash scripts/tests-start.sh
  
artifacts:
  files:
    - app/backend/htmlcov/**/*
  discard-paths: yes



