version: 0.2

phases:

  pre_build:
    commands:
      - echo "Now in dir $(pwd), contents $(ls)"
      - cd app/backend 
      - echo "Now in dir $(pwd), contents $(ls)"
      - echo "Installing uv"
      - curl -LsSf https://astral.sh/uv/install.sh | sh
      - source $HOME/.local/bin/env
      - echo "Installing project dependencies"
      - uv sync
      - echo "Activating virtualenv"
      - source .venv/bin/activate
  build:
    commands:
      - echo "Now in dir $(pwd), contents $(ls)"
      - echo "Starting services with docker compose"
      - docker compose up -d
      - echo "Checking service availability"
      - until [[ $(netstat -tlpn | grep 5432) ]]; do echo "waiting service"; sleep 2; done 
      - until [[ $(netstat -tlpn | grep 8000) ]]; do echo "waiting service"; sleep 2; done 
      - netstat -tlpn
      - echo "Running tests"
      - docker compose exec backend bash scripts/tests-start.sh
  
artifacts:
  files:
    - app/backend/htmlcov/**/*
  discard-paths: yes



