apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace.name }}
data:
  PROJECT_NAME: "Sample API"
  DOMAIN: "localhost"
  FRONTEND_HOST: "localhost"
  ENVIRONMENT: "local"
  BACKEND_CORS_ORIGINS: "http://localhost,http://localhost:8080,http://localhost:5173,https://localhost,https://localhost:5173,http://localhost.tiangolo.com"
  SECRET_KEY: "changethis"
  FIRST_SUPERUSER: "admin@example.com"
  FIRST_SUPERUSER_PASSWORD: "changethis"
  SMTP_HOST: ""
  SMTP_USER: ""
  SMTP_PASSWORD: ""
  EMAILS_FROM_EMAIL: info@example.com
  POSTGRES_SERVER: {{ .Values.configmap.data.db_host | quote }}
  POSTGRES_PORT: {{ .Values.configmap.data.db_port | quote }}
  POSTGRES_DB: {{ .Values.configmap.data.db_name | quote }}
  POSTGRES_USER: {{ .Values.db_cred.postgres_user | quote }}
  POSTGRES_PASSWORD: {{ .Values.db_cred.postgres_password | quote }}
  SENTRY_DSN: ""