apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: {{ .Values.namespace.name }}
data:
  PROJECT_NAME: "Sample API"
  DOMAIN: "localhost"
  FRONTEND_HOST: "localhost"
  ENVIRONMENT: "local"
  BACKEND_CORS_ORIGINS: "http://localhost,http://localhost:8080,http://localhost:5173,https://localhost,https://localhost:5173,http://localhost.tiangolo.com"
  SECRET_KEY: "changethis"
  FIRST_SUPERUSER: "admin@example.com"
  FIRST_SUPERUSER_PASSWORD: "changethis"
  SMTP_HOST: ""
  SMTP_USER: ""
  SMTP_PASSWORD: ""
  EMAILS_FROM_EMAIL: info@example.com
  POSTGRES_SERVER: "db-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "app"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "changethis"
  SENTRY_DSN: ""